FORMAT: 1A
HOST: http://webgis.nature.cz/aopkrest/lifecs/

# AOPK ČR - Life CS - Druhy a Biotopy

Rozhraní pro získávání informací o **druzích a biotopech na lokalitách life České středohoří**
 
## Seznam druhů a biotopů na lokalitách [/lokality/?f={f}]

+ Parameters
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + pjson - formátovaný json
            + json
            + html
            + xml

### Přehled [GET]

+ Response 200 (application/json)
    + Attributes (array[Lokalita])
    + Attributes (array[Lokalita])

## Číselníky [/ciselniky?f={f}]
+ Parameters
    + f (string, optional) - formát výstupu
        + Default: json
        + Members
            + json
            + pjson
            + html
            + xml

### Přehled [GET]

+ Response 200 (application/json)
    + Attributes (array[Ciselnik])
    + Attributes (array[Ciselnik])

## Změny [/zmeny/?f={f}]

+ Parameters
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + pjson - formátovaný json
            + json
            + html
            + xml

### Přehled [GET]

+ Response 200 (application/json)
    + Attributes (array[Zmena])
    + Attributes (array[Zmenna])
 

# Data Structures

##Lokalita
+ LokalitaId: 4 (number) - id lokality
+ Biotopy (array) - Výstupy viz zdroj dat v tabulce V_LF_BIOTOP - v popisu je uveden 
    + (Biotop)
    + (Biotop)
+ Druhy (array) - Výstupy viz zdroj dat v tabulce V_LF_DRUH - v popisu je uveden 
    + (Druh)
    + (Druh)

##Ciselnik
+ Biotopy (array)
    + (CisBiotop)
    + (CisBiotop)
+ Druhy (array) 
    + (CisDruh)
    + (CisDruh)


##Biotop
+ include CisBiotop
+ Rozloha (object)
    + RozlohaHodnota: 1164.5611 (number) - Rozloha biotopu - číselně 
    + RozlohaJednotka: ha (string) - Rozloha biotopu - jednotka 
    + UIValue: 1 164.561 ha (string) - rozloha biotopu zformátovaná pro výstup 
+ RozlohaRelativni: 18.8 (number) - relativní rozloha biotopu 
+ Kvalita: 2.12 (number) - Kvalita biotopu

##Druh
+ include CisBiotop
+ CervenySeznam: null (string) - Červený seznam 
+ RokPoslZaz: 2015 (number) - rok posledního záznamu 
+ DruhKarta: `http://portal.nature.cz/publik_syst/nd_nalez-public.php?idTaxon=4` (string) - odkaz na kartu druhu - jako odkaz z Latinský název druhu  `http://portal.nature.cz/publik_syst/nd_nalez-public.php?`

##CisBiotop
+ StanovisteKod: 91F0 (string) - Kód typu přírodního stanoviště 
+ StanovisteNazev: `Smíšené lužní lesy s dubem letním (Quercus robur) jilmem vazem (Ulmus laevis) a jilmem habrolistým (Ulmus minor) jasanem ztepilým (Fraxinus excelsior) nebo jasanem úzkolistým (Fraxinus angustifolia) podél velkých řek (Ulmenion minoris)` (string) - Název typu přírodního stanoviště * obsahuje formátování latinských názvů kurzívou <i></i>*
+ StanovisteNazevEn: `Riparian mixed forest of Quercus robur, Ulmus laevis and Ulmus minor, Fraxinus excelsior or Fraxinus angustifolia along the great rivers (Ulmenion minoris)` (string) - Název typu přírodního stanoviště v angličtině /NAME_HABITAT/ * obsahuje formátování latinských názvů kurzívou <i></i>*
+ BiotopKod: L2.3 (string) - Kód biotopu
+ BiotopNazev: Tvrdé luhy nížinných řek (string) - Název Biotopu  * obsahuje formátování latinských názvů kurzívou <i></i>*
+ BiotopNazevEn: Tvrdé luhy nížinných řek (string) - Název Biotopu v angličtině   * obsahuje formátování latinských názvů kurzívou <i></i>*

##CisDruh
+ TaxonId: 4 (number) - id taxonu
+ DruhKat: Obojživelníci (string) - Kategorie 
+ DruhNazevCz: ropucha obecná (string, optional) - Český název druhu
+ DruhNazevLat: Bufo bufo (string) - Latinský název druhu 
+ OchranaKat: Ohrožený (string) - Kategorie 
+ Smernice: null (string) -  

##CisLokalita

+ LokalitaId: 1 (number)- id lokality - cizí klíč do tabulek Druh a Biotop
+ LokalitaKat NK (string) - Kategorie 
    + NK 
    + EVL
+ LokalitaNazev Líska (string) 

##Zmena
+ Agenda: data (enum [string]) - kategorie chráněného území
    + Members
    + data - změna v seznamu druhů a biotopů
    + ciselniky - změna v číselnících 
+ Datum: `2018-05-14` (string) - datum poslední změny v dané agendě